//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashPayment
    {
        public int idPayment { get; set; }
        public int cod { get; set; }
        public int idPaymentLocation { get; set; }
    
        public virtual Payment Payment { get; set; }
        public virtual PaymentLocation PaymentLocation { get; set; }
    }
}
