//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class EventLocation
{
    public EventLocation()
    {
        this.Event = new HashSet<Event>();
    }

    public int id { get; set; }
    public string name { get; set; }
    public int phoneNumber { get; set; }
    public string address { get; set; }

    public virtual ICollection<Event> Event { get; set; }
}
