//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public System.DateTime date { get; set; }
        public double amount { get; set; }
        public int idReservation { get; set; }
    
        public virtual Reservation Reservation { get; set; }
        public virtual PaypalPayment PaypalPayment { get; set; }
        public virtual CashPayment CashPayment { get; set; }
    }
}
