//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(CashPayment))]
    [KnownType(typeof(Reservation))]
    [KnownType(typeof(PaypalPayment))]
    
    public partial class Payment
    {
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public System.DateTime date { get; set; }
    	[DataMember]
        public double mount { get; set; }
    	[DataMember]
        public int idReservation { get; set; }
    
    	[DataMember]
        public virtual CashPayment CashPayment { get; set; }
    	[DataMember]
        public virtual Reservation Reservation { get; set; }
    	[DataMember]
        public virtual PaypalPayment PaypalPayment { get; set; }
    }
}
