//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Payment))]
    
    public partial class PaypalPayment
    {
    	[DataMember]
        public int idPayment { get; set; }
    	[DataMember]
        public string transactionCod { get; set; }
    
    	[DataMember]
        public virtual Payment Payment { get; set; }
    }
}
