//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Reservation))]
    [KnownType(typeof(Ticket))]
    
    public partial class SubOrder
    {
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public byte active { get; set; }
    	[DataMember]
        public int idReservation { get; set; }
    	[DataMember]
        public int idTicket { get; set; }
    
    	[DataMember]
        public virtual Reservation Reservation { get; set; }
    	[DataMember]
        public virtual Ticket Ticket { get; set; }
    }
}
