//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(SubOrder))]
    [KnownType(typeof(TicketType))]
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.SubOrder = new HashSet<SubOrder>();
        }
    
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public int number { get; set; }
    	[DataMember]
        public int idTicketType { get; set; }
    
    	[DataMember]
        public virtual ICollection<SubOrder> SubOrder { get; set; }
    	[DataMember]
        public virtual TicketType TicketType { get; set; }
    }
}
