
//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace BO
{

using System;
    using System.Collections.Generic;
    
public partial class TicketType
{

    public TicketType()
    {

        this.Ticket = new HashSet<Ticket>();

    }


    public int id { get; set; }

    public double cost { get; set; }

    public string description { get; set; }

    public int startNum { get; set; }

    public int finalNum { get; set; }

    public int idEvent { get; set; }



    public virtual Event Event { get; set; }

    public virtual ICollection<Ticket> Ticket { get; set; }

}

}
