//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Event))]
    [KnownType(typeof(Ticket))]
    
    public partial class TicketType
    {
        public TicketType()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public double cost { get; set; }
    	[DataMember]
        public string description { get; set; }
    	[DataMember]
        public int startNum { get; set; }
    	[DataMember]
        public int finalNum { get; set; }
    	[DataMember]
        public int idEvent { get; set; }
    
    	[DataMember]
        public virtual Event Event { get; set; }
    	[DataMember]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
