//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Ticket
{
    public Ticket()
    {
        this.SubOrder = new HashSet<SubOrder>();
    }

    public int id { get; set; }
    public int number { get; set; }
    public int idTicketType { get; set; }

    public virtual ICollection<SubOrder> SubOrder { get; set; }
    public virtual TicketType TicketType { get; set; }
}
