//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BO
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract(IsReference = true)]
    [KnownType(typeof(Reservation))]
    
    public partial class User
    {
        public User()
        {
            this.Reservation = new HashSet<Reservation>();
        }
    
    	[DataMember]
        public int id { get; set; }
    	[DataMember]
        public string mail { get; set; }
    	[DataMember]
        public string password { get; set; }
    	[DataMember]
        public string name { get; set; }
    	[DataMember]
        public string lastName { get; set; }
    	[DataMember]
        public System.DateTime dateBirth { get; set; }
    	[DataMember]
        public byte userType { get; set; }
    	[DataMember]
        public int mobileNum { get; set; }
    
    	[DataMember]
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
