

//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DAL
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using BO;


public partial class TicketSaleEntities : DbContext
{
    public TicketSaleEntities()
        : base("name=TicketSaleEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<CashPayment> CashPayment { get; set; }

    public DbSet<Event> Event { get; set; }

    public DbSet<EventLocation> EventLocation { get; set; }

    public DbSet<Order> Order { get; set; }

    public DbSet<Payment> Payment { get; set; }

    public DbSet<PaymentLocation> PaymentLocation { get; set; }

    public DbSet<PaypalPayment> PaypalPayment { get; set; }

    public DbSet<Reservation> Reservation { get; set; }

    public DbSet<SubOrder> SubOrder { get; set; }

    public DbSet<Ticket> Ticket { get; set; }

    public DbSet<TicketType> TicketType { get; set; }

    public DbSet<User> User { get; set; }

    public DbSet<sysdiagrams> sysdiagrams { get; set; }

}

}

