//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWeb.PaypalServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaypalServiceClient.IPaypalService")]
    public interface IPaypalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaypalService/login", ReplyAction="http://tempuri.org/IPaypalService/loginResponse")]
        bool login(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaypalService/login", ReplyAction="http://tempuri.org/IPaypalService/loginResponse")]
        System.Threading.Tasks.Task<bool> loginAsync(string user, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaypalService/doPayment", ReplyAction="http://tempuri.org/IPaypalService/doPaymentResponse")]
        string doPayment(double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaypalService/doPayment", ReplyAction="http://tempuri.org/IPaypalService/doPaymentResponse")]
        System.Threading.Tasks.Task<string> doPaymentAsync(double amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaypalServiceChannel : AppWeb.PaypalServiceClient.IPaypalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaypalServiceClient : System.ServiceModel.ClientBase<AppWeb.PaypalServiceClient.IPaypalService>, AppWeb.PaypalServiceClient.IPaypalService {
        
        public PaypalServiceClient() {
        }
        
        public PaypalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaypalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaypalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaypalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool login(string user, string pass) {
            return base.Channel.login(user, pass);
        }
        
        public System.Threading.Tasks.Task<bool> loginAsync(string user, string pass) {
            return base.Channel.loginAsync(user, pass);
        }
        
        public string doPayment(double amount) {
            return base.Channel.doPayment(amount);
        }
        
        public System.Threading.Tasks.Task<string> doPaymentAsync(double amount) {
            return base.Channel.doPaymentAsync(amount);
        }
    }
}
